---
comments: false
subtitle: Curriculum Vitae
title: Dr Jonathan Carroll, PhD
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(dplyr)
```

# Education

```{r education}
```



# CRAN Packages

```{r CRAN rpkgs, results = 'asis'}
cran_pkgs <- pkgsearch::ps("Jonathan Carroll",size = 100) %>%
  filter(grepl("Jonathan Carroll", maintainer_name, fixed = TRUE)) %>%
  arrange(desc(downloads_last_month)) %>% 
  as.data.frame() %>% 
  select(-score, -starts_with("maintainer"), -package_data) %>% 
  mutate(description = encodeString(description),
         version = as.character(version),
         gitlab = sub("github", "gitlab", url))
rownames(cran_pkgs) <- cran_pkgs$package

glue::glue_data(cran_pkgs, "* [{package}](https://cran.r-project.org/package={package}) ..... [GitHub]({url}) | [GitLab]({gitlab})", sep = "\n")
```

# Development Packages

```{r github rpkgs, results = 'asis'}
library("ghql")
library("jsonlite")
library("httr")
token <- Sys.getenv("GITHUB_GRAPHQL_TOKEN")
cli <- GraphqlClient$new(
  url = "https://api.github.com/graphql",
  headers = add_headers(Authorization = paste0("Bearer ", token))
)
cli$load_schema()
qry <- Query$new()
qry$query('getdozedata', '{
  repositoryOwner(login:"jonocarroll") {
    repositories(first: 100, orderBy: {field:PUSHED_AT,direction:DESC}, isFork:false) {
      edges {
        node {
          name
          stargazers {
            totalCount
          }
        }
      }
    }
  }
}')
jsonlite::fromJSON(cli$exec(qry$queries$getdozedata))$data$repositoryOwner$repositories$edges$node %>% 
  mutate(stargazers = stargazers$totalCount) %>% 
  filter(stargazers > 0L) %>% 
  arrange(desc(stargazers)) %>% 
  knitr::kable()
```


# Academic Publications

```{r publications}
```